services:
    backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file: ./api/.env
        depends_on:
            - azclicredsproxy
        environment:
            - "IDENTITY_ENDPOINT=http://azclicredsproxy:8080/token"
            - "IMDS_ENDPOINT=dummy_required_value"
            - "SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true"
            - "SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true"
            - "AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED=true"
            - "AZURE_SDK_TRACING_IMPLEMENTATION=opentelemetry"
    frontend:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "8501:8501"
        env_file: ./web/.env
        depends_on:
            - backend
            - azclicredsproxy
        environment:
            - "services__api__api__0=http://backend:8000"
            - "IDENTITY_ENDPOINT=http://azclicredsproxy:8080/token"
            - "IMDS_ENDPOINT=dummy_required_value"
            - "SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true"
            - "SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true"
            - "AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED=true"
            - "AZURE_SDK_TRACING_IMPLEMENTATION=opentelemetry"
    azclicredsproxy:
        image: workleap/azure-cli-credentials-proxy:latest
        ports:
        - "8080:8080"
        volumes:
        #- "\\\\wsl$\\${DISTRONAME}\\home\\${USERNAME}\\.azure\\:/app/.azure/" # On Windows with WSL
        - "/home/${USERNAME}/.azure:/app/.azure/" # On Linux
        user: ${UID}:${GID}
